import os
from fastapi import FastAPI, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from typing import List

app = FastAPI(title="ContextSnap Cloud Engine")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/api/health")
def health():
    return {"status": "active", "tier": "cloud-stream"}

@app.post("/api/v1/upload-scan")
async def upload_codebase_scan(files: List[UploadFile] = File(...)):
    total_characters = 0
    file_contents = {}
    detected_frameworks = []
    
    inferred_root = "Uploaded_Repository"

    for file in files:
        # Read file paths generated by the webkit relative path selector
        rel_path = file.filename  # e.g., "my-app/src/App.jsx"
        
        # Pull the base root project folder name dynamically
        path_parts = rel_path.split('/')
        if path_parts and path_parts[0]:
            inferred_root = path_parts[0]

        try:
            # Read binary file layout into memory stream string safely
            content_bytes = await file.read()
            code = content_bytes.decode("utf-8", errors="ignore")
            
            char_count = len(code)
            total_characters += char_count
            
            # Keep trace track of text configurations for structural analysis
            if any(rel_path.endswith(ext) for ext in ['.py', '.js', '.jsx', '.ts', '.tsx', '.json', '.html', '.css']):
                file_contents[rel_path] = code
                
                # Check for stack definitions inside code blocks
                if "fastapi" in code.lower(): detected_frameworks.append("FastAPI (Python Backend)")
                if "react" in code.lower(): detected_frameworks.append("React (Frontend SPA)")
                if "express" in code.lower(): detected_frameworks.append("Express.js Server")
                if "tailwindcss" in code.lower() or '@import "tailwindcss"' in code: 
                    detected_frameworks.append("Tailwind CSS v4")
        except Exception:
            continue

    # Clean stack identification tags
    detected_frameworks = list(set(detected_frameworks)) if detected_frameworks else ["Generic Modular Source Architecture"]
    estimated_tokens = int(total_characters / 4)

    # --- DYNAMIC BLUEPRINT SIMULATION GENERATOR ---
    mermaid_nodes = []
    mermaid_edges = []
    
    for idx, path in enumerate(file_contents.keys()):
        clean_node_id = f"node_{idx}"
        filename = os.path.basename(path)
        mermaid_nodes.append(f'    {clean_node_id}["📄 {filename}<br/><small>{path}</small>"]')
        
        # Link UI components to central configuration targets
        if "main.py" in filename or "index" in filename or "App" in filename:
            for target_idx, target_path in enumerate(file_contents.keys()):
                if target_idx != idx and ("service" in target_path or "api" in target_path or "config" in target_path):
                    mermaid_edges.append(f'    {clean_node_id} --> node_{target_idx}')

    nodes_str = "\n".join(mermaid_nodes[:15]) # Cap visual rendering layout at 15 key file layers for display readability
    edges_str = "\n".join(mermaid_edges[:12])
    
    if not edges_str and len(mermaid_nodes) > 1:
        edges_str = "    node_0 --> node_1"

    generated_mermaid = f"graph TD\n{nodes_str}\n{edges_str}"
    
    system_summary = (
        f"This project represents a fully self-contained application using "
        f"{', '.join(detected_frameworks)}. The cloud runtime mapped {len(files)} ingested file targets "
        f"and calculated structural relationships securely in-memory."
    )

    return {
        "metrics": {
            "root": inferred_root,
            "total_files": len(files),
            "estimated_tokens": estimated_tokens
        },
        "blueprint": {
            "summary": system_summary,
            "mermaid_chart": generated_mermaid,
            "frameworks": detected_frameworks
        }
    }